name: build

on:
  push:
    branches: 
        - '**'
jobs:
  checkstyle_job:

    runs-on: ubuntu-latest
    name: Checkstyle job
    container: debian:sid

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          checkstyle_config: checkstyle.xml
          fail_on_error: true
          level: error
